Vagrant.configure("2") do |config|
  config.vm.define "rancher" do |rancher|
    rancher.vm.box = "ubuntu/focal64"
    rancher.vm.hostname = "rancher"
    rancher.vm.network "private_network", ip: "192.168.56.20"
    rancher.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.cpus = "4"
    end
  end

  config.vm.define "master1" do |master1|
    master1.vm.box = "ubuntu/focal64"
    master1.vm.hostname = "master1"
    master1.vm.network "private_network", ip: "192.168.56.21"
    master1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end

  config.vm.define "worker1" do |worker1|
    worker1.vm.box = "ubuntu/focal64"
    worker1.vm.hostname = "worker1"
    worker1.vm.network "private_network", ip: "192.168.56.22"
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.box = "ubuntu/focal64"
    worker2.vm.hostname = "worker2"
    worker2.vm.network "private_network", ip: "192.168.56.23"
  end
end